version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      day: "wednesday"
      time: "08:00"
      timezone: "America/Vancouver"
    labels:
      - "dependencies"
    versioning-strategy: widen

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      day: "wednesday"
      time: "08:00"
      timezone: "America/Vancouver"
    labels:
      - "actions"
      - "dependencies"
